### ISSUE TITLE
compileShell does not work without a "laniakea" profile in ~/.boto

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#1]
compileShell should detect the presence of:

1. ~/.boto
2. "laniakea" profile in ~/.boto

and still continue to work with/without any of them.

```
[sstangl@kupo funfuzz]$ python -u js/compileShell.py -b "--enable-debug --enable-more-deterministic --enable-nspr-build -R ~/dev/mozilla-central"
Traceback (most recent call last):
  File "js/compileShell.py", line 750, in <module>
    main()
  File "js/compileShell.py", line 746, in main
    obtainShell(shell, updateToRev=options.revision)
  File "js/compileShell.py", line 665, in obtainShell
    useS3Cache = s3CacheObj.connect()
  File "/home/sstangl/dev/funfuzz/util/s3cache.py", line 52, in connect
    conn = S3Connection(profile_name=EC2_PROFILE)
  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 190, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 555, in __init__
    profile_name)
  File "/usr/lib/python2.7/site-packages/boto/provider.py", line 200, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/usr/lib/python2.7/site-packages/boto/provider.py", line 296, in get_credentials
    profile_name)
boto.provider.ProfileNotFoundError: Profile "laniakea" not found!
```

**Comment by nth10sd** [comment]
This seems to occur when (1) on Linux, (2) boto is installed in python located on $PATH, and credentials are not found in ~/.boto .
