### ISSUE TITLE
[funfuzz] When FuzzManager server is down, retry after a longer period of time

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#145]
```
Server unexpectedly responded with status code 503: 
Unable to find required entries in .fuzzmanagerconf, exiting...

Something went wrong when calling: ['/Users/fuzz7/trees/venv-fm/bin/python', '-u', '-m', 'funfuzz.bot', '-b', '--random', '--target-time', '28800']
CalledProcessError()
Traceback (most recent call last):
  File "/Users/fuzz7/trees/venv-fm/lib/python2.7/site-packages/funfuzz/loop_bot.py", line 32, in loop_seq
    subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/Users/fuzz7/trees/venv-fm/bin/python', '-u', '-m', 'funfuzz.bot', '-b', '--random', '--target-time', '28800']' returned non-zero exit status 1
```

funfuzz retries after a few minutes when the server returns a 503 error. We should probably increase this timeout period, probably to 15 or 30 mins.

**Comment by nth10sd** [comment]
An exponential backoff algorithm was implemented in rev b0c65106.
