### ISSUE TITLE
[autobisectjs] Cached busted shells do not allow testing for earliest known working build

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#209]
```
$ date && time python3 -m funfuzz.autobisectjs -b "--enable-debug --build-with-clang" -l bad && date
Fri Aug  3 19:56:58 PDT 2018
WARNING: This set of build options is not tested well because: Clang builds on Windows are not supported well yet.
Note: since no parameters were specified, we're just ensuring the shell does not crash on startup/shutdown.
Fri Aug  3 19:57:03 2018 | Bisecting on: c:\Users\<username>\trees\mozilla-central
Rev 4e56a2f51ad7: Found cached shell...
Testing... good (Exit code 0)  Finished testing the initial boundary revisions... This iteration took 0.219 seconds to run.
Traceback (most recent call last):
  File "c:\mozilla-build\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\mozilla-build\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\autobisectjs\__main__.py", line 13, in <module>
    main()
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\autobisectjs\autobisectjs.py", line 540, in main
    findBlamedCset(options, repo_dir, compile_shell.makeTestRev(options))
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\autobisectjs\autobisectjs.py", line 243, in findBlamedCset
    label = testRev(currRev)
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 633, in testRev
    obtainShell(shell, updateToRev=rev)
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 657, in obtainShell
    raise Exception("Found a cached shell that failed compilation...")
Exception: Found a cached shell that failed compilation...
Rev 530f7bd28399:
real    0m9.310s
user    0m0.000s
sys     0m0.000s
```

**Comment by nth10sd** [comment]
This was fixed by rev 8986bbecbbb3ef31f57d2e16054fdda4ebdcf032 ...
