### ISSUE TITLE
Unable to find required entries in FuzzManager. Duplicate detection via sigcache will not work...

### ISSUE THREAD

**Issue by Implementist** [MozillaSecurity/funfuzz#215]
I installed FuzzManager via using `pip install FuzzManager` and finished configuring funfuzz . The root folder of my Ubuntu server is `/home/nisl/` and I created a file as `/home/nisl/.fuzzmanagerconf` which contains content like:
```
[Main]
sigdir = /home/nisl/sigcache/
serverhost = 127.0.0.1
serverport = 8000
serverproto = https
tool = jsfunfuzz
```
When I run `python -u funfuzz/loop_bot.py -b "--random" --target-time 28800 | tee ~/log-loop_botPy.txt` in `/home/nisl/funfuzz/src/` I always get an error like:
```
Unable to find required entries in FuzzManager. Duplicate detection via sigcache will not work...
/tmp/tmp962g_8cyfuzzbot
ERROR:boto:Caught exception reading instance data
Traceback (most recent call last):
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

Could anybody who tells me how to fix it?

**Comment by nth10sd** [comment]
Does this still occur if you install funfuzz requirements (FuzzManager included) using:

```pip install --upgrade -r requirements.txt```

? Ideally you should create a virtualenv from Python 3 via `-m venv`.

**Comment by Implementist** [comment]
I did that and get the error again. But when I open the new, only one file in shell-cache here is the content:
```
Configuration of mozilla-central rev f6df375b8698 failed with the following output:
sh: 0: Can't open /home/nisl/trees/mozilla-central/js/src/configure

Caught exception CalledProcessError(127, ['sh', '/home/nisl/trees/mozilla-central/js/src/configure', '--target=i686-pc-linux', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests']) (Command '['sh', '/home/nisl/trees/mozilla-central/js/src/configure', '--target=i686-pc-linux', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests']' returned non-zero exit status 127.)
Backtrace:
Traceback (most recent call last):
  File "/home/nisl/funfuzz/src/funfuzz/js/compile_shell.py", line 672, in obtainShell
    cfgJsCompile(shell)
  File "/home/nisl/funfuzz/src/funfuzz/js/compile_shell.py", line 334, in cfgJsCompile
    cfgBin(shell)
  File "/home/nisl/funfuzz/src/funfuzz/js/compile_shell.py", line 529, in cfgBin
    stdout=subprocess.PIPE).stdout.decode("utf-8", errors="replace")
  File "/home/nisl/anaconda3/envs/py3.6_env/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', '/home/nisl/trees/mozilla-central/js/src/configure', '--target=i686-pc-linux', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests']' returned non-zero exit status 127.
```

I opened `/home/nisl/trees/mozilla-central/js/src/` but found that there have not a file named configure. The most similar one is configure.in.

**Comment by nth10sd** [comment]
At least we're making progress.

I have not tried with anaconda before. Do you mind creating a virtualenv using the `-m venv` method, then repeating the steps?

Assuming you're on 18.04 Bionic, you could try:

```
python3 -m venv ~/venv-funfuzz
pushd ~/funfuzz && ~/venv-funfuzz/bin/pip install --upgrade -r requirements.txt && popd
# This should test compilation only, as opposed to compilation + fuzzing for funfuzz.bot
~/venv-funfuzz/bin/python -m funfuzz.js.compile_shell -b "--enable-debug --enable-more-deterministic"
```

**Comment by Implementist** [comment]
OK, I will try it and report the result later.

**Comment by Implementist** [comment]
Mr. Kwong,
    Because of the server I used before can not run `venv` method correctly, I created a virtual machine of Ubuntu 16.04. With both `conda` and `python -m venv` I configured funfuzz two times again. But I got the same Error `Can't open /home/nisl/trees/mozilla-central/js/src/configure`.
    Is it necessary to run these commands under Ubuntu 18.04?

**Comment by nth10sd** [comment]
Yes, they are needed to compile the shell. I'm not sure why `configure` cannot be accessed now. Perhaps a permissions issue? They should all be run under the `ubuntu` user.

I won't really support 16.04 going forward, everything should be proceeding towards 18.04.

**Comment by Implementist** [comment]
Thanks for your help up to now. I will try it again under a Ubuntu 18.04 emvironment and report the result later.
