### ISSUE TITLE
Error running fuzz

### ISSUE THREAD

**Issue by shubham0d** [MozillaSecurity/funfuzz#230]
Hi,
I have done the installation of funfuzz using the README file. Now when I am trying to run 
the funfuzz with following parameters `funfuzz -b "--random" --target-time 28800 | tee ~/log-loop_botPy.txtcd`. I am getting this error:
```
Platform details: Linux 0day-Hackintosh 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64
hg info: Mercurial Distributed SCM (version 4.9.1)
gdb info: GNU gdb (Ubuntu 8.2-0ubuntu1~18.04) 8.2
git info: git version 2.17.1
Python version: 3.6.7
Number of cores visible to OS: 3
Free space (GB): 9.58
Corefile size (soft limit, hard limit) is: (0, -1)

Unable to find required entries in FuzzManager. Duplicate detection via sigcache will not work...
/tmp/tmp9w1x0kx7fuzzbot
Traceback (most recent call last):
  File "/home/shubham/.local/bin/funfuzz", line 11, in <module>
    load_entry_point('funfuzz==0.7.0a1', 'console_scripts', 'funfuzz')()
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/bot.py", line 114, in main
    build_info = ensureBuild(options)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/bot.py", line 186, in ensureBuild
    compile_shell.obtainShell(cshell, updateLatestTxt=updateLatestTxt)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/js/compile_shell.py", line 651, in obtainShell
    raise OSError("Found a cached shell that failed compilation...")
OSError: Found a cached shell that failed compilation...
```

I tried changing default python version to python3 but then I receive following error.
```
Traceback (most recent call last):
  File "/usr/local/bin/hg", line 43, in <module>
    dispatch.run()
  File "/usr/lib/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python2.7/dist-packages/mercurial/dispatch.py", line 22, in <module>
    from .i18n import _
  File "/usr/lib/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "/usr/local/lib/python2.7/dist-packages/mercurial/i18n.py", line 104, in <module>
    if _plain():
  File "/usr/local/lib/python2.7/dist-packages/mercurial/i18n.py", line 98, in _plain
    if ('HGPLAIN' not in encoding.environ
  File "/usr/lib/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "/usr/local/lib/python2.7/dist-packages/mercurial/encoding.py", line 24, in <module>
    charencode = policy.importmod(r'charencode')
  File "/usr/local/lib/python2.7/dist-packages/mercurial/policy.py", line 101, in importmod
    mod = _importfrom(pn, mn)
  File "/usr/local/lib/python2.7/dist-packages/mercurial/policy.py", line 57, in _importfrom
    pkg = __import__(pkgname, globals(), fakelocals, [modname], level=1)
  File "/usr/lib/python3.6/importlib/util.py", line 274, in create_module
    return self.loader.create_module(spec)
ImportError: /usr/local/lib/python2.7/dist-packages/mercurial/cext/parsers.so: undefined symbol: _Py_ZeroStruct
Platform details: Linux 0day-Hackintosh 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64
Traceback (most recent call last):
  File "/home/shubham/.local/bin/funfuzz", line 11, in <module>
    load_entry_point('funfuzz==0.7.0a1', 'console_scripts', 'funfuzz')()
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/bot.py", line 100, in main
    print_machine_info()
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/bot.py", line 135, in print_machine_info
    stdout=subprocess.PIPE).stdout.decode("utf-8", errors="replace").rstrip()
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['hg', '-q', 'version']' returned non-zero exit status 1.
```

**Comment by nth10sd** [comment]
With the first `OSError: Found a cached shell that failed compilation...` error, remove the `~/shell-cache` directory and try again.

With your second error, make sure `hg version` works properly first. You may have to install Mercurial via `python -m pip install --user --upgrade mercurial` initially.

When Mercurial finally moves to Python 3, I'll set Mercurial as a required package in `setup.py` but for now, while funfuzz and dependent libraries are on Python 3, Mercurial is the only one that still requires 2.

**Comment by shubham0d** [comment]
Thanks for the solution. I have removed `~/shell-cache` directory and the error disappear but then another issue appears.
```
Platform details: Linux 0day-Hackintosh 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64
hg info: Mercurial Distributed SCM (version 4.9.1)
gdb info: GNU gdb (Ubuntu 8.2-0ubuntu1~18.04) 8.2
git info: git version 2.17.1
Python version: 3.6.7
Number of cores visible to OS: 3
Free space (GB): 9.55
Corefile size (soft limit, hard limit) is: (0, -1)

Unable to find required entries in FuzzManager. Duplicate detection via sigcache will not work...
/tmp/tmpmf_e91wtfuzzbot
Unable to connect via boto using profile name "laniakea" in ~/.boto
Compiling...
Compilation failed (Command '['sh', '/home/shubham/trees/mozilla-central/js/src/configure', '--target=i686-pc-linux', '--disable-profiling', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests', '--disable-cranelift']' returned non-zero exit status 1.) (details in /home/shubham/shell-cache/js-32-profDisabled-dm-linux-x86_64-a17f163841e9/js-32-profDisabled-dm-linux-x86_64-a17f163841e9.busted)
Traceback (most recent call last):
  File "/home/shubham/.local/bin/funfuzz", line 11, in <module>
    load_entry_point('funfuzz==0.7.0a1', 'console_scripts', 'funfuzz')()
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/bot.py", line 114, in main
    build_info = ensureBuild(options)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/bot.py", line 186, in ensureBuild
    compile_shell.obtainShell(cshell, updateLatestTxt=updateLatestTxt)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/js/compile_shell.py", line 700, in obtainShell
    cfgJsCompile(shell)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/js/compile_shell.py", line 335, in cfgJsCompile
    cfgBin(shell)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/js/compile_shell.py", line 544, in cfgBin
    stdout=subprocess.PIPE).stdout.decode("utf-8", errors="replace")
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', '/home/shubham/trees/mozilla-central/js/src/configure', '--target=i686-pc-linux', '--disable-profiling', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests', '--disable-cranelift']' returned non-zero exit status 1.
```

**Comment by nth10sd** [comment]
The logfile should be in the `shell-cache` subdirectories with the `.busted` file extension. Can you post the log?

(Also, please ensure you have installed Firefox build prerequisites)

**Comment by shubham0d** [comment]
Attaching the logs:
```
Configuration of mozilla-central rev 02b89c29412b failed with the following output:
Creating Python environment
New python executable in /home/shubham/shell-cache/js-dbg-64-dm-armsim64-linux-x86_64-02b89c29412b/objdir-js/_virtualenvs/init/bin/python2.7
Also creating executable in /home/shubham/shell-cache/js-dbg-64-dm-armsim64-linux-x86_64-02b89c29412b/objdir-js/_virtualenvs/init/bin/python
Installing setuptools, pip, wheel...done.
running build_ext
building 'psutil._psutil_linux' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/psutil
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/psutil
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/psutil/_psutil_common.o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o -o build/lib.linux-x86_64-2.7/psutil/_psutil_linux.so
building 'psutil._psutil_posix' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=543 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/psutil/_psutil_common.o build/temp.linux-x86_64-2.7/psutil/_psutil_posix.o -o build/lib.linux-x86_64-2.7/psutil/_psutil_posix.so
copying build/lib.linux-x86_64-2.7/psutil/_psutil_linux.so -> psutil
copying build/lib.linux-x86_64-2.7/psutil/_psutil_posix.so -> psutil

Error processing command. Ignoring because optional. (optional:packages.txt:comm/build/virtualenv_packages.txt)
Reexecuting in the virtualenv
checking for vcs source checkout... hg
checking for a shell... /bin/sh
checking for host system type... x86_64-pc-linux-gnu
checking for target system type... x86_64-pc-linux-gnu
checking for Python 3... /usr/bin/python3 (3.6.7)
checking for hg... /usr/bin/hg
checking for Mercurial version... 4.5.3
checking for sparse checkout... no
checking whether cross compiling... no
checking for yasm... /usr/bin/yasm
checking yasm version... 1.3.0
checking for ccache... not found
DEBUG: ccache: Trying ccache
ERROR: Cannot find ccache

Caught exception CalledProcessError(1, ['sh', '/home/shubham/trees/mozilla-central/js/src/configure', '--enable-simulator=arm64', '--enable-debug', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests', '--disable-cranelift']) (Command '['sh', '/home/shubham/trees/mozilla-central/js/src/configure', '--enable-simulator=arm64', '--enable-debug', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests', '--disable-cranelift']' returned non-zero exit status 1.)
Backtrace:
Traceback (most recent call last):
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/js/compile_shell.py", line 700, in obtainShell
    cfgJsCompile(shell)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/js/compile_shell.py", line 335, in cfgJsCompile
    cfgBin(shell)
  File "/home/shubham/.local/lib/python3.6/site-packages/funfuzz/js/compile_shell.py", line 544, in cfgBin
    stdout=subprocess.PIPE).stdout.decode("utf-8", errors="replace")
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', '/home/shubham/trees/mozilla-central/js/src/configure', '--enable-simulator=arm64', '--enable-debug', '--enable-more-deterministic', '--with-ccache', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests', '--disable-cranelift']' returned non-zero exit status 1.
```

**Comment by nth10sd** [comment]
Try installing ccache?

**Comment by shubham0d** [comment]
yes installed it. But get getting similar error.

**Comment by nth10sd** [comment]
Try commenting [this line](https://github.com/MozillaSecurity/funfuzz/blob/53f775133151fa6faa8847a84a75f5c7680a772e/src/funfuzz/js/compile_shell.py#L489) and its following line out.

Also, I'm not sure if I support this type of system: `Linux 0day-Hackintosh 4.18.0-17-generic`...

**Comment by shubham0d** [comment]
Hi, 
Thanks for the solution.
I have setup the environment in new machine, commented the line and the program starts running correctly.
