### ISSUE TITLE
jsInteresting throws when Values instance has no attribute 'jsengineWithArgs'

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#28]
$ time ~/trees/venv-fm/bin/python -u ~/funfuzz/js/compareJIT.py --minlevel=4 --flags="--fuzzing-safe --non-writable-jitcode --no-cgc --gc-zeal=4 --no-asmjs --thread-count=32" mozilla-central ~/shell-cache/js-dbg-64-dm-clang-linux-211a4c710fb6/js-dbg-64-dm-clang-linux-211a4c710fb6 bb187169.js
/tmp/tmpneu5NVcompareJITmain-r0 |   3.5s | 0 | fine
/tmp/tmpneu5NVcompareJITmain-r1 |   3.5s | 0 | fine
/tmp/tmpneu5NVcompareJITmain-r2 |   1.0s | 0 | fine
/tmp/tmpneu5NVcompareJITmain-r3 |   0.9s | 0 | fine
/tmp/tmpneu5NVcompareJITmain-r4 |   0.9s | 0 | fine
/tmp/tmpneu5NVcompareJITmain-r5 |   2.8s | 0 | fine
/tmp/tmpneu5NVcompareJITmain-r6 |   0.9s | 0 | fine
/tmp/tmpneu5NVcompareJITmain-r7 |   4.0s | 0 | fine

crashInfo:
  Short Signature: Assertion failure: !cx->isExceptionPending(), at /home/ubuntu/trees/mozilla-central/js/src/jscntxt.cpp:335

  Class name: GDBCrashInfo
  Stack trace: ['js::ReportOutOfMemory', 'js::SourceCompressionTask::complete', 'js::SourceCompressionTask::~SourceCompressionTask', 'mozilla::Maybe<js::SourceCompressionTask>::reset', 'mozilla::Maybe<js::SourceCompressionTask>::~Maybe', 'BytecodeCompiler::~BytecodeCompiler', 'js::frontend::CompileScript', 'Compile', 'Compile', 'JS::Compile', 'Evaluate', 'js::CallJSNative', 'js::Invoke', 'Interpret', 'js::RunScript', 'js::Invoke', 'js::Invoke', 'js::jit::DoCallFallback', '??', '??', '??', '??', 'js::jit::DoCallNativeSetterInfo', '??', '??', '??', '??', '??', '??']

/tmp/tmpneu5NVcompareJITmain-r8 |   1.7s | 5 | new assert or crash
Traceback (most recent call last):
  File "/home/ubuntu/funfuzz/js/compareJIT.py", line 260, in <module>
    main()
  File "/home/ubuntu/funfuzz/js/compareJIT.py", line 258, in main
    print compareLevel(options.jsengine, options.flags, options.infilename, tempfile.mkdtemp("compareJITmain"), options, True, False)[0]
  File "/home/ubuntu/funfuzz/js/compareJIT.py", line 93, in compareLevel
    r = jsInteresting.ShellResult(options, command, prefix, True)
  File "/home/ubuntu/funfuzz/js/jsInteresting.py", line 129, in __init__
    'Command: ' + sps.shellify(options.jsengineWithArgs) + '\n'] +
AttributeError: Values instance has no attribute 'jsengineWithArgs'

real    0m25.910s
user    0m24.956s
sys     0m0.896s

**Comment by nth10sd** [comment]
This happens because options.jsengineWithArgs is not present in the options object of compareJIT, but is present in the options object of jsInteresting.

@jruderman what is the best way of fixing this? I can think of:
* Adding a jsengineWithArgs parameter to the options object of compareJIT, and/or define it to be the value of options.flagsSpaceSep
* Being "smart" in jsInteresting such that if options.jsengineWithArgs does not exist, use options.flags

**Comment by nth10sd** [comment]
Now hitting this in production:

```
Traceback (most recent call last):
File "/home/ubuntu/funfuzz/autobisect-js/autoBisect.py", line 911, in <module> main()
File "/home/ubuntu/funfuzz/autobisect-js/autoBisect.py", line 901, in main compileShell.makeTestRev(options))
File "/home/ubuntu/funfuzz/autobisect-js/autoBisect.py", line 232, in findBlamedCset label = testRev(currRev) File "/home/ubuntu/funfuzz/js/compileShell.py", line 591, in testRev return options.testAndLabel(shell.getShellCacheFullPath(), rev)
File "/home/ubuntu/funfuzz/autobisect-js/autoBisect.py", line 331, in inner if conditionScript.interesting(conditionArgs, tempPrefix):
File "/home/ubuntu/funfuzz/js/compareJIT.py", line 255, in interesting actualLevel = compareLevel(gOptions.jsengine, gOptions.flags, gOptions.infilename, tempPrefix, gOptions, False, False)[0]
File "/home/ubuntu/funfuzz/js/compareJIT.py", line 97, in compareLevel r = jsInteresting.ShellResult(options, command, prefix, True)
File "/home/ubuntu/funfuzz/js/jsInteresting.py", line 130, in __init__ 'Command: ' + sps.shellify(options.jsengineWithArgs) + '\n'] + AttributeError: Values instance has no attribute 'jsengineWithArgs' 
```

**Comment by nth10sd** [comment]
This is causing potential Q0s to show up as Q10s for some reason.
