### ISSUE TITLE
running loopbot command in readme fails

### ISSUE THREAD

**Issue by crowell** [MozillaSecurity/funfuzz#30]
```
(fuzzer)termina ~ » python -u funfuzz/loopBot.py -b "--random" --target-time 28800 | tee ~/log-loopBotPy.txt
localLoop #1!
INFO:__main__:Fri Mar 18 17:49:08 2016
Updating FuzzManager ...
Running `git pull --rebase` now..
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.

`git pull --rebase` took 0.037 seconds.

Updating funfuzz ...
Running `git pull --rebase` now..
Current branch master is up to date.

`git pull --rebase` took 0.539 seconds.

Updating lithium ...
Running `git pull --rebase` now..
Current branch master is up to date.

`git pull --rebase` took 0.396 seconds.

Updating mozilla-central ...
Running `hg pull -u` now..
pulling from https://hg.mozilla.org/mozilla-central/
searching for changes
no changes found

`hg pull -u` took 1.679 seconds.

Running `hg log -r default` now..
changeset:   289323:9c5d494d0548
tag:         tip
fxtree:      central
parent:      289178:3d37c7e5b8dd
parent:      289322:51803770c37d
user:        Carsten "Tomcat" Book <cbook@mozilla.com>
date:        Fri Mar 18 15:51:43 2016 +0100
summary:     merge mozilla-inbound to mozilla-central a=merge



`hg log -r default` took 0.610 seconds.

INFO:__main__:Fri Mar 18 17:49:11 2016
Platform details: Linux termina 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64
hg version: Mercurial Distributed SCM (version 3.7.2)
gdb version: GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Python version: 2.7.10
Number of cores visible to OS: 4
Free space (GB): 579.63
Corefile size (soft limit, hard limit) is: (0, -1)
Traceback (most recent call last):
  File "/home/jeff/funfuzz/bot.py", line 309, in <module>
    main()
  File "/home/jeff/funfuzz/bot.py", line 135, in main
    refreshSignatures(collector)
  File "/home/jeff/funfuzz/bot.py", line 201, in refreshSignatures
    collector.refresh()
  File "/home/jeff/FuzzManager/Collector/Collector.py", line 54, in decorator
    raise RuntimeError("Must specify serverHost (configuration property: serverhost) to use remote features.")
RuntimeError: Must specify serverHost (configuration property: serverhost) to use remote features.
Something went wrong when calling: ['/home/jeff/fuzzer/bin/python', '-u', '/home/jeff/funfuzz/bot.py', '-b', '--random', '--$
arget-time', '28800']
Traceback (most recent call last):
  File "funfuzz/loopBot.py", line 44, in loopSequence
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/home/jeff/fuzzer/bin/python', '-u', '/home/jeff/funfuzz/bot.py', '-b', '--random', '--target-
time', '28800']' returned non-zero exit status 1

Waiting 60 seconds...
```

clean checkouts of all directories.

setting the serverhost in FuzzManager's ~/.fuzzmanager.conf

https://gist.github.com/6595ddb384db0e979803

gives this traceback

```
INFO:__main__:Fri Mar 18 17:50:22 2016
Platform details: Linux termina 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64
hg version: Mercurial Distributed SCM (version 3.7.2)
gdb version: GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Python version: 2.7.10
Number of cores visible to OS: 4
Free space (GB): 579.63
Corefile size (soft limit, hard limit) is: (0, -1)
Traceback (most recent call last):
  File "/home/jeff/funfuzz/bot.py", line 309, in <module>
    main()
  File "/home/jeff/funfuzz/bot.py", line 135, in main
    refreshSignatures(collector)
  File "/home/jeff/funfuzz/bot.py", line 199, in refreshSignatures
    collector.refreshFromZip(os.path.expanduser("~/FuzzManager/server/files/signatures.zip"))
  File "/home/jeff/FuzzManager/Collector/Collector.py", line 67, in decorator
    return f(self, *args, **kwargs)
  File "/home/jeff/FuzzManager/Collector/Collector.py", line 180, in refreshFromZip
    with ZipFile(zipFileName, "r") as zipFile:
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/home/jeff/FuzzManager/server/files/signatures.zip'
Something went wrong when calling: ['/home/jeff/fuzzer/bin/python', '-u', '/home/jeff/funfuzz/bot.py', '-b', '--random', '--target-time', '28800']
Traceback (most recent call last):
  File "funfuzz/loopBot.py", line 44, in loopSequence
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/home/jeff/fuzzer/bin/python', '-u', '/home/jeff/funfuzz/bot.py', '-b', '--random', '--target-time', '28800']' returned non-zero exit status 1

Waiting 60 seconds...
```

**Comment by nth10sd** [comment]
bot.py is getting into:
```
collector.refreshFromZip(os.path.expanduser("~/FuzzManager/server/files/signatures.zip"))
```
because of:
```
if collector.serverHost == "127.0.0.1"
```
which I presume @jruderman was using to test FuzzManager integration during early days of the fmi branch.

Jesse, what is the best way forward here? Shall we remove this if block?

**Comment by jruderman** [comment]
Do you have the FuzzManager cron job set up to create signatures.zip?

I think that branch is still needed for the non-Apache version of FuzzManager, which doesn't know how to serve zip files. But it should start with the parent of path0 instead of assuming FuzzManager is in ~.

**Comment by crowell** [comment]
no cronjob was set up, just cloned the required repos into my homedir and ran the python script in the readme. This is on the first pass, firefox never even gets built with this setup.

**Comment by jruderman** [comment]
I hope that commit helps. See https://github.com/MozillaSecurity/FuzzManager/#server-cronjobs for a more complete list of cronjobs that a production instance of FuzzManager would use.

**Comment by nth10sd** [comment]
Closing, assuming that commit did help.
