### ISSUE TITLE
crash requests to fuzzmanager causes traceback

### ISSUE THREAD

**Issue by crowell** [MozillaSecurity/funfuzz#31]
ran fuzzer for a few hours, got this traceback when i reattached.

```
[22/Mar/2016 22:04:53] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xc1\x03Zn\xb7&\x10\xc3\x99\xe0\xed\xa7\xc8\xe5\xdc\xcc3\xb8\x19\xf6
S~\xf7\x90r\xc0*')
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58422)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 129, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 124, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/home/jeff/fuzzer/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 136, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 9: ordinal not in range(128)
----------------------------------------
```

**Comment by nth10sd** [comment]
hmmm none of the items on the stack involve anything about funfuzz.

**Comment by choller** [comment]
Is this trace on the server? What kind of server are you running? It seems to me that you are sending non-ascii data somewhere where it attempts to log data as ascii, but without the request you performed there it will be hard to figure out the cause.

**Comment by crowell** [comment]
that's the trace from the server. the server is just the default django python server (no apache in front or anything) launched `python manage.py runserver` I don't know which request sent this data, as the only thing in my `logs` dir is `ec2spotmanager.log` which is empty as i'm not using ec2

**Comment by nth10sd** [comment]
Try again with later versions of FuzzManager? Moreover this does not seem to be an issue with funfuzz, so closing. Please feel free to file new issues with the corresponding project going forward.
