### ISSUE TITLE
[loopjsfunfuzz] Collector submission of metadata throws

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#32]
Traceback (most recent call last):
  File "c:\mozilla-build\python\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\mozilla-build\python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\fuzz1win\funfuzz\util\forkJoin.py", line 48, in redirectOutputAndCallFun
    fun(*(someArgs + (i,)))
  File "c:\Users\fuzz1win\funfuzz\bot.py", line 278, in loopFuzzingAndReduction
    loopjsfunfuzz.many_timed_runs(options.targetTime, tempDir, buildInfo.mtrArgs, collector)
  File "c:\Users\fuzz1win\funfuzz\js\loopjsfunfuzz.py", line 205, in many_timed_runs
    collector.submit(res.crashInfo, filenameToReduce, quality, metadata=metadata)
  File "c:\Users\fuzz1win\FuzzManager\Collector\Collector.py", line 59, in decorator
    return f(self, *args, **kwargs)
TypeError: submit() got an unexpected keyword argument 'metadata'

This happened on Windows, but I suspect it might affect other platforms too.

**Comment by nth10sd** [comment]
The issue is that the submit function within Collector accepts "metaData" as a keyword and not "metadata":

https://github.com/MozillaSecurity/FuzzManager/blob/4b40299/Collector/Collector.py#L194
