### ISSUE TITLE
[funfuzz] Log actual compile error in .busted file

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#33]
@choller mentioned that currently when compilations are busted, the compile error isn't logged, but rather only the fact that compilation failed. Let's log the compile error itself as well.

**Comment by nth10sd** [comment]
On Windows, I only seem to see these:

```
Caught exception CalledProcessError(1, ['sh', 'c://Users//<username>//trees//mozilla-central//js//src//configure', '--host=x86_64-pc-mingw32', '--target=x86_64-pc-mingw32', '--disable-jemalloc', '--enable-debug', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests']) (Command '['sh', 'c://Users//<username>//trees//mozilla-central//js//src//configure', '--host=x86_64-pc-mingw32', '--target=x86_64-pc-mingw32', '--disable-jemalloc', '--enable-debug', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests']' returned non-zero exit status 1.)
Backtrace:
Traceback (most recent call last):
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 700, in obtainShell
    cfgJsCompile(shell)
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 350, in cfgJsCompile
    cfgBin(shell)
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 547, in cfgBin
    stdout=subprocess.PIPE).stdout.decode("utf-8", errors="replace")
  File "c:\mozilla-build\python3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sh', 'c://Users//<username>//trees//mozilla-central//js//src//configure', '--host=x86_64-pc-mingw32', '--target=x86_64-pc-mingw32', '--disable-jemalloc', '--enable-debug', '--enable-gczeal', '--enable-debug-symbols', '--disable-tests']' returned non-zero exit status 1.
```

and

```
Caught exception OSError('mozmake did not result in a js shell.',) (mozmake did not result in a js shell.)
Backtrace:
Traceback (most recent call last):
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 700, in obtainShell
    cfgJsCompile(shell)
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 360, in cfgJsCompile
    sm_compile(shell)
  File "c:\mozilla-build\python3\lib\site-packages\funfuzz\js\compile_shell.py", line 622, in sm_compile
    raise OSError(MAKE_BINARY + " did not result in a js shell.")
OSError: mozmake did not result in a js shell.
```
