### ISSUE TITLE
No such file or directory: ../FuzzManager/server/files/signatures.zip

### ISSUE THREAD

**Issue by juneJuly** [MozillaSecurity/funfuzz#44]
$ python -u funfuzz/loopBot.py -b "--random" -t "js" --target-time 28800 | tee ~/log-loopBotPy.txt
localLoop #1!
cmd:['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '-u', '/Users/username/funfuzz/bot.py', '-b', '--random', '-t', 'js', '--target-time', '28800']
Platform details: Darwin -Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64 i386
hg version: Mercurial Distributed SCM (version 3.6.2)
gdb version: GNU gdb (GDB) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin13.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Python version: 2.7.7
Number of cores visible to OS: 8
Free space (GB): 92.00
Corefile size (soft limit, hard limit) is: (0, 9223372036854775807)
Traceback (most recent call last):
  File "/Users/username/funfuzz/bot.py", line 299, in <module>
    main()
  File "/Users/username/funfuzz/bot.py", line 118, in main
    refreshSignatures(collector)
  File "/Users/username/funfuzz/bot.py", line 186, in refreshSignatures
    collector.refreshFromZip(os.path.join(path0, "..", "FuzzManager", "server", "files", "signatures.zip"))
  File "/Users/username/FuzzManager/Collector/Collector.py", line 67, in decorator
    return f(self, *args, **kwargs)
  File "/Users/username/FuzzManager/Collector/Collector.py", line 180, in refreshFromZip
    with ZipFile(zipFileName, "r") as zipFile:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/Users/username/funfuzz/../FuzzManager/server/files/signatures.zip'

**Comment by juneJuly** [comment]
OK, i fixed this.
