### ISSUE TITLE
Deal with gdb crashing (and generating a coredump) instead of the shell crashing

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#7]
The original fix for gdb crashing (and generating a coredump) in https://github.com/MozillaSecurity/funfuzz/commit/b6b54b017932f280b3edb67b0d730eca542f6844 causes the following exception and is now backed out.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gkwong/fuzzing/util/forkJoin.py", line 48, in redirectOutputAndCallFun
    fun(*(someArgs + (i,)))
  File "/home/gkwong/fuzzing/bot.py", line 591, in fuzzUntilBug
    (lithResult, lithDetails) = loopjsfunfuzz.many_timed_runs(options.targetTime, job, buildInfo.mtrArgs)
  File "/home/gkwong/fuzzing/js/loopjsfunfuzz.py", line 158, in many_timed_runs
    level = jsInteresting.jsfunfuzzLevel(jsunhappyOptions, logPrefix)
  File "/home/gkwong/fuzzing/js/jsInteresting.py", line 131, in jsfunfuzzLevel
    (lev, issues, runinfo) = baseLevel(options.jsengineWithArgs, options.timeout, options.knownPath, logPrefix, valgrind=options.valgrind)
  File "/home/gkwong/fuzzing/js/jsInteresting.py", line 72, in baseLevel
    sps.grabCrashLog(runthis[0], runinfo.pid, logPrefix, True)
  File "/home/gkwong/fuzzing/util/subprocesses.py", line 261, in grabCrashLog
    preexec_fn=(disableCorefile if os.name == 'posix' else None)  # Do not generate a corefile if gdb crashes
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory 
```

We should still fix this.

**Comment by nth10sd** [comment]
I reverted the backout in rev https://github.com/MozillaSecurity/funfuzz/commit/571ba971f6797ef243bddeeb0625bcef372e0d39 - turns out that the cause was unrelated.

The machine was freshly imaged recently and did not have gdb installed.
