### ISSUE TITLE
[funfuzz] loopBot.py/bot.py fails with no apparent reason when .fuzzmanagerconf is not found

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#99]
If we run loopBot.py or bot.py, either through crontab or otherwise, without a .fuzzmanagerconf present in the user directory for example, the harness will fail without a useful stack pointing to the absence of a .fuzzmanagerconf file.

**Comment by nth10sd** [comment]
e.g. when I renamed the corresponding `.fuzzmanagerconf` file of a particular build to test, the stack thrown is:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/util/fork_join.py", line 62, in redirectOutputAndCallFun
    fun(*(someArgs + (i,)))
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/bot.py", line 220, in loopFuzzingAndReduction
    loop.many_timed_runs(options.targetTime, tempDir, buildInfo.mtrArgs, collector)
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/js/loop.py", line 148, in many_timed_runs
    engineFlags = shell_flags.random_flag_set(options.jsEngine)  # pylint: disable=invalid-name
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/js/shell_flags.py", line 213, in random_flag_set
    if shell_supports_flag(shell_path, "--fuzzing-safe"):  # This is always enabled if supported
  File "/home/winworklin/.local/lib/python2.7/site-packages/functools32/functools32.py", line 378, in wrapper
    result = user_function(*args, **kwds)
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/js/shell_flags.py", line 51, in shell_supports_flag
    out = inspect_shell.shellSupports(shell_path, [flag] + dummy_parameters)
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/js/inspect_shell.py", line 119, in shellSupports
    return_code = testBinary(shellPath, args, False)[1]
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/js/inspect_shell.py", line 139, in testBinary
    os.path.dirname(os.path.abspath(shellPath))))
  File "/home/winworklin/.local/lib/python2.7/site-packages/funfuzz/util/subprocesses.py", line 74, in captureStdout
    raise Exception(repr(e.strerror) + ' error calling: ' + shellify(cmd))
Exception: 'No such file or directory' error calling: mozilla-central --fuzzing-safe -e 42
```

This stack was obtained when testing on top of PR #169.

**Comment by nth10sd** [comment]
I'll stick in an assert that the `.fuzzmanagerconf` file should be present before the call to the `FuzzManager` library.
